[package]
name = "playnow_daemon"
version = "0.1.0"
authors = ["XMPPwocky <nttheis@gmail.com>"]

[dependencies]
hyper = "0.6.13"
serde = "*"
serde_json = "*"
steamwebapi = "*"

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"
